### ISSUE TITLE
Sample rule is not CCCS valid

### ISSUE THREAD

**Issue by BitsOfBinary** [CybercentreCanada/CCCS-Yara#28]
The following meta tag in the sample rule in the README.md file is not CCCS valid:
```
technique = "LOADER:MEMORYMODULE"
```
This is due to the colon in place. Removing this colon makes the rule valid, but I'm not sure if that is what is intended.

**Comment by cccs-gm** [comment]
Thank you for bringing this to our attention. I will make the necessary adjustments tomorrow.

**Comment by cccs-jp** [comment]
Resolved in latest release: https://github.com/CybercentreCanada/CCCS-Yara/releases/tag/v1.3
