### ISSUE TITLE
Bug: Invalid yara rules pass validation

### ISSUE THREAD

**Issue by JohnConnorRF** [CybercentreCanada/CCCS-Yara#38]
Yara validation appears to succeed when the rule doesn't contain a closing bracket. Example yara rule: 

```
rule APT_CN_TestYara {
   meta:
      description = "Detect malware"
      author = "TEST"
      date = "2021-01-12"
      version = "1.0"

   strings:
      $s1 = "test"
   condition:
      $s1
```

In case its relevant, there is no newline at the end of the file. This was tested using the default CCCS_YARA.yml file from commit (91e66c4)

**Comment by cccs-gm** [comment]
Thank you for bringing this bug to our attention. I am currently looking it the best method of catching it.

**Comment by cccs-gm** [comment]
Interestingly this is the first case of a malformed yara rule that the plyara library didn't return an error for. I expect the fix to be rolled out tomorrow.

**Comment by cccs-gm** [comment]
We have added a new branch with the [bug fix](https://github.com/CybercentreCanada/CCCS-Yara/tree/bugfix_invalid_yara_rules_pass_validation). It is undergoing review but I expect it will be setup to merge soon.

Thank you again for bringing this to our attention.

**Comment by cccs-gm** [comment]
Sorry for the delay @JohnConnorRF. The bug fix ended up creating some issues of its own. This will catch the case you brought up and should potentially catch some others in the future.

**Comment by cccs-gm** [comment]
To clarify the fix is live in master. We plan to have a new release later this week.
