### ISSUE TITLE
Issue with import modules

### ISSUE THREAD

**Issue by GlennHD** [CybercentreCanada/CCCS-Yara#48]
When validating Yara rules with imported modules, the validator appears to fail. Any ideas?

```bash
$ cat ~/test.yara
```
```python

import "pe"

rule test
{
    meta:
    condition:
        pe.number_of_resources > 1
}
```
```bash
$ python yara_validator_cli.py -v ~/test.yara
```
```
Validating Rule file:                   /root/test.yara
🍩 Invalid Rule File:                   /root/test.yara
     - Errors:
       - test.yara:                     Error Compiling YARA file with yara:    'line 6: syntax error'

```

**Comment by cccs-rs** [comment]
This might be problem with rule itself or maybe YARA doesn't have the PE module enabled?

Try:
`python -c 'import yara; yara.compile("~/test.yara")'`

**Comment by GlennHD** [comment]
Thanks. Was certainly a yara issue. Fixed by uninstalling yara and building from source. Thanks!
