### ISSUE TITLE
README Suggestions

### ISSUE THREAD

**Issue by jxb5151** [CybercentreCanada/CCCS-Yara#74]
When creating a PR I noticed the README documentation seems to be out of date.

- Documentation suggests using `yara_validator_cli.py`. However that does not appear to exist when installing via the latest from master. Setup.py appears to install this component as `yara_validator`. May need to switch the README to just `yara_validator` instead and update associated usage.
- Also noticed the library `yara_validator.py` appears to have been changed to just `validator.py` but is still referenced using the old name. 

I'd toss in a PR candidate for this, but my French is not so great. Depending on the desired documentation updates being made, would require more than I can offer in that department! :)

**Comment by cccs-rs** [comment]
Thanks for noticing! I must've forgotten that part when I was getting this package-ready to push to PyPI 😅
